name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Ruff Check
        uses: astral-sh/ruff-action@v3
        with:
          src: "."

      - name: Run Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          src: "."
          args: "format --check"
